parameters:
  name: Gonzalo
  deep:
    second: [1,2,3]
    third: [a,b,c]

services:
  App:
    class:     App
    scope: prototype
    lazy: true
    arguments: [@Proxy, %name%]
    calls:
        - [setName, ['Yolo']]
    configurator: ['@Configurator', configure]
    tags: [{ name: konfigurator.node }]

    
  Proxy:
    class:     Proxy
    lazy: true
    arguments: [@Curl]
    
  Curl:
    class:     Curl
    lazy: true

  Configurator:
    class:     Test